# A primeira seção define os "serviços" que rodam código.
services:
  - type: web
    name: ponto-eletronico
    env: java
    plan: free
    buildCommand: "chmod +x mvnw && ./mvnw clean install"
    startCommand: "java -jar target/ponto-eletronico-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
          property: internalConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
          property: password

# A segunda seção, separada, define os bancos de dados.
databases:
  - name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
    plan: free