services:
  # Define o nosso Web Service (o site)
  - type: web
    name: ponto-eletronico
    env: java
    plan: free
    buildCommand: "chmod +x mvnw && ./mvnw clean install"
    startCommand: "java -jar target/ponto-eletronico-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
          property: internalConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
          property: password

  # Define o nosso Banco de Dados
  - type: database   # <-- A INSTRUÇÃO CORRIGIDA! (Era 'psql')
    name: ponto-db-leo # <-- Verifique se este é o nome do seu banco
    plan: free